apiVersion: v1
kind: Namespace
metadata:
  name: manga-reader
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: manga-reader-nfs-config
  namespace: manga-reader
data:
  NFS_SERVER: "REPLACE_ME"
  NFS_PATH_PGDATA: "REPLACE_ME"
  NFS_PATH_CACHE: "REPLACE_ME"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: manga-reader-domain-config
  namespace: manga-reader
data:
  WEB_DOMAIN: "REPLACE_ME"
  IMG_DOMAIN: "REPLACE_ME"
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server-service
  namespace: manga-reader
spec:
  type: ExternalName
  externalName: REPLACE_ME
---
apiVersion: v1
kind: Secret
metadata:
  name: manga-reader-secrets
  namespace: manga-reader
stringData:
  POSTGRES_USER: "REPLACE_ME"
  POSTGRES_PASSWORD: "REPLACE_ME"

  WEB_DB_USER: "REPLACE_ME"
  WEB_DB_PASSWORD: "REPLACE_ME"
  WEB_DATABASE_URL: "postgres://$(WEB_DB_USER):$(WEB_DB_PASSWORD)@manga-reader-postgres:5432/manga_db"

  PROCESSOR_DB_USER: "REPLACE_ME"
  PROCESSOR_DB_PASSWORD: "REPLACE_ME"
  PROCESSOR_DB_URL: "postgresql://$(PROCESSOR_DB_USER):$(PROCESSOR_DB_PASSWORD)@manga-reader-postgres:5432/image_processor"

  BETTER_AUTH_SECRET: "REPLACE_ME"
  BETTER_AUTH_URL: "REPLACE_ME"
  DISCORD_CLIENT_ID: "REPLACE_ME"
  DISCORD_CLIENT_SECRET: "REPLACE_ME"

  S3_ACCESS_KEY_ID: "any"
  S3_SECRET_ACCESS_KEY: "any"

  IMAGE_SERVER_API_KEY: "REPLACE_ME"
  BOT_SECRET: "REPLACE_ME"
  MAIL_USER: "REPLACE_ME"
  POSTFIX_PASSWORD: "REPLACE_ME"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: manga-reader-web-config
  namespace: manga-reader
data:
  IMAGE_SERVER_URL_INNER: "http://image-processor-service.manga-reader.svc.cluster.local:3001"
  MAIL_HOST: "nfs-server-service"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: image-processor-config
  namespace: manga-reader
data:
  PORT: "3001"
  HOST: "0.0.0.0"
  UPLOADS_DIR: "/uploads"
  BACKUP_MOUNT_DIR: "/backup"
  SHARED_SSD_CACHE_DIR: "/cache"
  SHARED_SSD_CACHE_DURATION_IN_SECONDS: "3600"
  CACHE_MAX_AGE: "2592000"
  MAX_UPLOAD_SIZE: "1073741824"
  BACKTRACK_DURATION_IN_SECONDS: "172800"
  RAM_CACHE_EXPIRY_DURATION: "3600"
  MAX_RAM_CACHE_SIZE: "20"
  MAX_SHARED_SSD_SIZE_GB: "10"
  S3_ENDPOINT: "http://nfs-server-service:18333"
  S3_BUCKET_NAME: "image-save"
  S3_VIRTUAL_HOSTED_STYLE: "false"
  API_KEY: "REPLACE_ME"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: manga-reader
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
        CREATE USER ${WEB_DB_USER} WITH PASSWORD '${WEB_DB_PASSWORD}';
        CREATE DATABASE manga_db;
        GRANT ALL PRIVILEGES ON DATABASE manga_db TO ${WEB_DB_USER};
        
        CREATE USER ${PROCESSOR_DB_USER} WITH PASSWORD '${PROCESSOR_DB_PASSWORD}';
        CREATE DATABASE image_processor;
        GRANT ALL PRIVILEGES ON DATABASE image_processor TO ${PROCESSOR_DB_USER};
    EOSQL

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "manga_db" -c "GRANT ALL ON SCHEMA public TO ${WEB_DB_USER};"
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "image_processor" -c "GRANT ALL ON SCHEMA public TO ${PROCESSOR_DB_USER};"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manga-pgdata-pvc
  namespace: manga-reader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: manga-uploads-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: 192.168.0.101
    path: /mnt/ssd/share/image-server/uploads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manga-uploads-pvc
  namespace: manga-reader
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
  volumeName: manga-uploads-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: manga-cache-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: 192.168.0.101
    path: /mnt/ssd/share/image-server/cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manga-cache-pvc
  namespace: manga-reader
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
  volumeName: manga-cache-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manga-reader-postgres
  namespace: manga-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: postgres
            - name: WEB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: WEB_DB_USER
            - name: WEB_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: WEB_DB_PASSWORD
            - name: PROCESSOR_DB_USER
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: PROCESSOR_DB_USER
            - name: PROCESSOR_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: PROCESSOR_DB_PASSWORD
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: manga-pgdata-pvc
        - name: init-script
          configMap:
            name: postgres-init-script
---
apiVersion: v1
kind: Service
metadata:
  name: manga-reader-postgres
  namespace: manga-reader
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manga-reader-webserver
  namespace: manga-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nc -z manga-reader-postgres 5432; do echo waiting for postgres; sleep 2; done;",
            ]
      containers:
        - name: manga-reader
          image: home.local/manga-reader-web:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: manga-reader-web-config
          env:
            - name: WEB_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: manga-reader-domain-config
                  key: WEB_DOMAIN
            - name: IMG_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: manga-reader-domain-config
                  key: IMG_DOMAIN
            - name: IMAGE_SERVER_URL
              value: "https://$(IMG_DOMAIN)"
            - name: BETTER_AUTH_URL
              value: "https://$(WEB_DOMAIN)"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: WEB_DATABASE_URL
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: BETTER_AUTH_SECRET
            - name: DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: DISCORD_CLIENT_ID
            - name: DISCORD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: DISCORD_CLIENT_SECRET
            - name: IMAGE_SERVER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: IMAGE_SERVER_API_KEY
            - name: BOT_SECRET
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: BOT_SECRET
            - name: MAIL_USER
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: MAIL_USER
            - name: POSTFIX_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: POSTFIX_PASSWORD
            - name: NODE_ENV
              value: production
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads
            - name: cache-volume
              mountPath: /cache
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: manga-uploads-pvc
        - name: cache-volume
          persistentVolumeClaim:
            claimName: manga-cache-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: manga-reader-web-service
  namespace: manga-reader
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processor-deployment
  namespace: manga-reader
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-processor
  template:
    metadata:
      labels:
        app: image-processor
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nc -z manga-reader-postgres 5432; do echo waiting for postgres; sleep 2; done;",
            ]
      containers:
        - name: image-processor
          image: home.local/manga-reader-image-processor:latest
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          envFrom:
            - configMapRef:
                name: image-processor-config
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: PROCESSOR_DB_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: PROCESSOR_DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: PROCESSOR_DB_PASSWORD
            - name: POSTGRES_DB
              value: "image_processor"
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: S3_ACCESS_KEY_ID
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: manga-reader-secrets
                  key: S3_SECRET_ACCESS_KEY
          volumeMounts:
            - name: uploads-volume
              mountPath: /uploads
            - name: cache-volume
              mountPath: /cache
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: manga-uploads-pvc
        - name: cache-volume
          persistentVolumeClaim:
            claimName: manga-cache-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: image-processor-service
  namespace: manga-reader
spec:
  selector:
    app: image-processor
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manga-reader-ingress
  namespace: manga-reader
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: manga-reader-manga-reader-limit@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: pazik.win
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: manga-reader-web-service
                port:
                  number: 80
    - host: image.pazik.win
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: image-processor-service
                port:
                  number: 3001
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: manga-reader-limit
  namespace: manga-reader
spec:
  buffering:
    maxRequestBodyBytes: 1073741824
